### ISSUE TITLE
Broken on 19w38b

### ISSUE THREAD

**Issue by Fuyukai** [shedaniel/Cloth#20]
Seems like there's been a significant amount of rendering-relating stuff changed.

```
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [cloth.mixins.json:MixinGameRenderer] from phase [DEFAULT] in config [cloth.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinError(MixinTransformer.java:779)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinApplyError(MixinTransformer.java:732)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:513)
	... 12 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @Inject annotation on handler$renderCenter$zdm000 could not find any targets matching 'renderCenter' in the target class net.minecraft.client.render.GameRenderer. No refMap loaded.
```

I imagine you probably already know this, but just in case...

**Comment by shedaniel** [comment]
Yep I already know this, but thanks anyways ^~^
