### ISSUE TITLE
[Mod conflict] Crashes with Better Slabs AND Iron Jetpacks

### ISSUE THREAD

**Issue by K0-RR** [shedaniel/Cloth#30]
Reported to [Iron Jetpacks](https://github.com/shedaniel/IronJetpacks/issues/7) and [Better Slabs](https://github.com/Eilux/BetterSlabs/issues/12) too

crash report - https://hatebin.com/pkfqoyvpmg
latest.log:
```
[13:34:52] [main/INFO]: Loading for game Minecraft 1.16.4
[13:34:52] [ForkJoinPool-1-worker-1/WARN]: The mod "autoconfig1u" contains invalid entries in its mod json:
- Unsupported root entry "$schema" at line 2 column 14
[13:34:52] [main/INFO]: [FabricLoader] Loading 63 mods: fabric-renderer-api-v1@0.3.3+6a2618f53a, fabric-keybindings-v0@0.2.0+6a2618f53a, cloth-common-events-v1@1.4.9, fabricloader@0.10.8, artifice@0.14.4+1.16.3, fabric-structure-api-v1@1.1.1+f1d8af063a, fabric-containers-v0@0.1.9+a03e98793a, cloth-durability-bar-api-v1@1.4.9, iron-jetpacks@0.2.6, fabric-object-builder-api-v1@1.9.2+6a2618f53a, fabric-dimensions-v1@2.0.1+9a6c75813a, fabric-game-rule-api-v1@1.0.3+a4467d2a3a, fabric-api-base@0.2.0+ab87788d3a, fabric-rendering-data-attachment-v1@0.1.4+6a2618f53a, cloth-dynamic-registry-api-v1@1.4.9, fabric-textures-v0@1.0.5+6a2618f53a, fabric-rendering-fluids-v1@0.1.12+6a2618f53a, cloth-scissors-api-v1@1.4.9, fabric-blockrenderlayer-v1@1.1.4+6a2618f53a, fabric-lifecycle-events-v1@1.2.0+ffb68a873a, cardinal-components-util@2.7.5, fabric-renderer-registries-v1@2.2.0+6a2618f53a, fabric-loot-tables-v1@1.0.1+6a2618f53a, fabric@0.28.0+1.16, cloth-armor-api-v1@1.4.9, fabric-particles-v1@0.2.2+6a2618f53a, fabric-networking-v0@0.3.0+a03e98793a, fabric-screen-handler-api-v1@1.1.0+6a2618f53a, minecraft@1.16.4, fabric-networking-blockentity-v0@0.2.7+a03e98793a, modmenu@1.14.13+build.19, cloth-basic-math@0.5.1, fabric-command-api-v1@1.0.9+6a2618f53a, cloth-utils-v1@1.4.9, fabric-tool-attribute-api-v1@1.2.5+6a2618f53a, fabric-renderer-indigo@0.4.3+6a2618f53a, cloth-client-events-v0@1.4.9, fabric-item-api-v1@1.2.0+6a2618f53a, fabric-events-interaction-v0@0.4.1+6a2618f53a, fabric-crash-report-info-v1@0.1.2+b7f9825d3a, statement@4.0.0+1.16.2, fabric-rendering-v0@1.1.1+6a2618f53a, fabric-rendering-v1@1.4.0+6a2618f53a, fabric-key-binding-api-v1@1.0.1+730711c63a, fabric-resource-loader-v0@0.3.2+1944f3e03a, autoconfig1u@3.2.0-unstable, fabric-content-registries-v0@0.2.0+e77439c73a, fabric-tag-extensions-v0@1.1.0+e77439c73a, fabric-biome-api-v1@3.1.0+2e23b97c3a, cardinal-components-entity@2.7.5, cloth-api@1.4.9, fabric-registry-sync-v0@0.7.2+a03e98793a, fabric-commands-v0@0.2.0+6a2618f53a, cardinal-components-base@2.7.5, fabric-mining-levels-v0@0.1.2+6a2618f53a, cloth-datagen-api-v1@1.4.9, fabric-networking-api-v1@1.0.0+4358fbc63a, fabric-events-lifecycle-v0@0.2.0+6a2618f53a, fabric-models-v0@0.1.1+6a2618f53a, fabric-item-groups-v0@0.2.1+6a2618f53a, fabric-object-builders-v0@0.7.1+6a2618f53a, team_reborn_energy@0.1.0, betterslabs@1.1.3
[13:34:52] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/home/k0rr/.local/share/multimc/libraries/net/fabricmc/sponge-mixin/0.8.2+build.24/sponge-mixin-0.8.2+build.24.jar Service=Knot/Fabric Env=CLIENT
[13:34:56] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[13:34:57] [main/INFO]: Setting user: _K0RR_
[13:34:58] [main/INFO]: Mod 'cloth-scissors-api-v1' uses the modmenu:clientsideOnly custom value unnecessarily, as it can be inferred from the mod's declared environment.
[13:34:58] [main/INFO]: [Indigo] Registering Indigo renderer!
[13:34:59] [main/INFO]: Backend library: LWJGL version 3.2.2 build 10
[13:35:00] [main/WARN]: Removed resource pack fabric/sodium from options because it doesn't seem to exist anymore
[13:35:01] [main/INFO]: Narrator library successfully loaded
[13:35:01] [main/INFO]: Reloading ResourceManager: Default, Fabric Loader, Fabric Game Rule API (v1), Fabric API Base, Fabric Networking (v0), Mod Menu, Fabric Crash Report Info (v1), Fabric Key Binding API (v1), Fabric Object Builder API (v1), Fabric Rendering Data Attachment (v1), Fabric Lifecycle Events (v1), Fabric Loot Tables (v1), Fabric Command API (v1), Fabric Renderer - Indigo, Fabric Rendering (v0), Fabric Rendering (v1), Fabric Tag Extensions (v0), Fabric Events Lifecycle (v0), Fabric Key Bindings (v0), Fabric BlockRenderLayer Registration (v1), Fabric API, Fabric Screen Handler API (v1), Fabric Tool Attribute API (v1), Fabric Events Interaction (v0), Fabric Resource Loader (v0), Fabric Registry Sync (v0), Fabric Mining Levels (v0), Fabric Item Groups (v0), Fabric Models (v0), Fabric Renderer API (v1), Fabric Containers (v0), Fabric Textures (v0), Fabric Rendering Fluids (v1), Fabric Renderer Registries (v1), Fabric Networking Block Entity (v0), Fabric Item API (v1), Fabric Content Registries (v0), Fabric Biome API (v1), Fabric Object Builders (v0), VanillaTweaks_r545341.zip, Artifice, Auto Config v1 Updated, Betterslabs, Fabric Networking API (v1), Iron Jetpacks, Statement, Energy
[13:35:04] [Worker-Main-8/WARN]: Exception loading blockstate definition: 'minecraft:blockstates/kelp.json' in resourcepack: 'VanillaTweaks_r545341.zip' for variant: 'normal': Unknown blockstate property: 'normal'
[13:35:06] [Worker-Main-10/ERROR]: Using missing texture, unable to load minecraft:textures/item/crossbow.png : java.io.FileNotFoundException: minecraft:textures/item/crossbow.png
[13:35:06] [Worker-Main-8/WARN]: Texture minecraft:custom/note_block/4 with size 36x36 limits mip level from 4 to 2
[13:35:06] [Worker-Main-8/WARN]: minecraft:textures/atlas/blocks.png: dropping miplevel from 4 to 2, because of minimum power of two: 4
[13:35:07] [main/INFO]: OpenAL initialized.
[13:35:07] [main/INFO]: Sound engine started
[13:35:08] [main/INFO]: Created: 2048x1024x2 minecraft:textures/atlas/blocks.png-atlas
[13:35:08] [main/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[13:35:08] [main/INFO]: Created: 1024x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[13:35:08] [main/INFO]: Created: 1024x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[13:35:08] [main/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[13:35:08] [main/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[13:35:08] [main/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[13:35:09] [main/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[13:35:09] [main/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[13:35:09] [main/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[13:35:11] [main/FATAL]: Unreported exception thrown!
java.lang.NullPointerException: null
	at com.swordglowsblue.artifice.impl.ArtificeResourcePackImpl.toClientResourcePackProfile(ArtificeResourcePackImpl.java:447) ~[a55f8593-8bcb-449a-8d36-173d87216559.jar:?]
	at com.swordglowsblue.artifice.impl.ArtificeAssetsResourcePackProvider.method_14453(ArtificeAssetsResourcePackProvider.java:20) ~[a55f8593-8bcb-449a-8d36-173d87216559.jar:?]
	at net.minecraft.class_3283.method_29212(class_3283.java:44) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_3283.method_14445(class_3283.java:37) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_310.method_1521(class_310.java:815) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1003) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:681) [intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:215) [intermediary-minecraft-1.16.4-client.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_275]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_275]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_275]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_275]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224) [fabric-loader-0.10.8.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141) [fabric-loader-0.10.8.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27) [fabric-loader-0.10.8.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_275]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_275]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_275]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_275]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]

```

**Comment by K0-RR** [comment]
I know this probably isn't cloth-api issue but I'm not sure, I ain't a programmer.

**Comment by shedaniel** [comment]
not cloth
