### ISSUE TITLE
Config UI crashes

### ISSUE THREAD

**Issue by Dekamir** [shedaniel/Cloth#4]
https://hastebin.com/ocinebeyaf.makefile

Happens when Cloth's config is clicked (via modlist or REI)

**Comment by shedaniel** [comment]
Please update / downgrade your cloth to your respective snapshot

**Comment by Dekamir** [comment]
They were already 19w14b, but Cloth Event API got updated 5 hours ago.
After updating Cloth Event API, the client doesn't boot:
`java.lang.NoClassDefFoundError: me/shedaniel/cloth/api/ConfigScreenBuilder
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at me.shedaniel.rei.RoughlyEnoughItemsCore.onInitializeClient(RoughlyEnoughItemsCore.java:96)
	at java.util.ArrayList.forEach(Unknown Source)
	at net.fabricmc.loader.entrypoint.hooks.EntrypointClient.start(EntrypointClient.java:35)
	at net.minecraft.class_310.method_1503(class_310.java)
	at net.minecraft.class_310.method_1514(class_310.java:395)
	at net.minecraft.client.main.Main.main(Main.java:154)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:130)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassNotFoundException: me.shedaniel.cloth.api.ConfigScreenBuilder
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:148)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 22 more`

Also added Cloth Config API afterwards, but it doesn't change anything for the time being.

**Comment by shedaniel** [comment]
Cloth Config holds a different API, get versions before 0.3.0 in Cloth Event for now
