### ISSUE TITLE
MC 1.18.1 crashed when loading a combination of Fabulously Optimized 3.2.6 and Valhesia: Enhanced Vanilla 1.1.2

### ISSUE THREAD

**Issue by SansSkele76** [shedaniel/Cloth#51]
Initial Crash Message:
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Config 'class me.shedaniel.slightguimodifications.config.SlightGuiModificationsConfig' has not been registered
Exit Code: -1

Full Crash Log:
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 4/30/22, 6:42 PM
Description: Initializing game

java.lang.RuntimeException: Config 'class me.shedaniel.slightguimodifications.config.SlightGuiModificationsConfig' has not been registered
	at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.22)
	at me.shedaniel.autoconfig.AutoConfig.getConfigHolder(AutoConfig.java:77)
	at me.shedaniel.slightguimodifications.SlightGuiModifications.getGuiConfig(SlightGuiModifications.java:314)
	at net.minecraft.client.MinecraftClient.modify$gbc000$getGuiScale(MinecraftClient:29005)
	at net.minecraft.client.MinecraftClient.onResolutionChanged(MinecraftClient:1232)
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient:615)
	at net.minecraft.client.main.Main.main(Main:199)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at me.shedaniel.autoconfig.AutoConfig.getConfigHolder(AutoConfig.java:77)
	at me.shedaniel.slightguimodifications.SlightGuiModifications.getGuiConfig(SlightGuiModifications.java:314)
	at net.minecraft.class_310.modify$gbc000$getGuiScale(class_310.java:29005)
	at net.minecraft.class_310.method_15993(class_310.java:1232)
	at net.minecraft.class_310.<init>(class_310.java:615)

-- Initialization --
Details:
	Modules: ~~ERROR~~ LinkageError: loader constraint violation: when resolving interface method 'int com.sun.jna.platform.win32.Version.GetFileVersionInfoSize(java.lang.String, com.sun.jna.ptr.IntByReference)' the class loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @255b53dc of the current class, net/minecraft/class_6498, and the class loader 'app' for the method's defining class, com/sun/jna/platform/win32/Version, have different Class objects for the type com/sun/jna/ptr/IntByReference used in the signature (net.minecraft.class_6498 is in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @255b53dc, parent loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader$DynamicURLClassLoader @731f8236; com.sun.jna.platform.win32.Version is in unnamed module of loader 'app')
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:199)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 956950832 bytes (912 MiB) / 2185232384 bytes (2084 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 2
	Microarchitecture: unknown
	Frequency (GHz): 2.59
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: Intel(R) UHD Graphics
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x9bc4
	Graphics card #0 versionInfo: DriverVersion=26.20.100.7985
	Graphics card #1 name: NVIDIA GeForce GTX 1650 Ti
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x1f95
	Graphics card #1 versionInfo: DriverVersion=30.0.14.9649
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 24684.60
	Virtual memory used (MB): 16357.84
	Swap memory total (MB): 16705.60
	Swap memory used (MB): 2240.68
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m
	Fabric Mods: 
		additionaladditions: Additional Additions 4.0.0
		advanced_runtime_resource_pack: Runtime Resource Pack 0.5.4
		advancementinfo: AdvancementInfo 1.18-fabric0.43.1-1.3
		advancementplaques: Advancement Plaques 1.4.4
		advancementscreenshot-fabric: Advancement Screenshot (Fabric) 3.2
		adventurez: AdventureZ 1.4.9
		ae2: Applied Energistics 2 10.1.0-beta.3
		ambientenvironment: Ambient Environment 7.0+17
		amecsapi: Amecs API 1.3.6+mc1.18-pre1
		anchor: Anchor 1.0.1
		animal_feeding_trough: Animal Feeding Trough 1.0.3+1.18.1
		animatica: Animatica 0.4+1.18
		antighost: AntiGhost 1.18-fabric0.43.1-1.1.4
		appleskin: AppleSkin 2.3.0+mc1.18.1
		arcanus: Arcanus 1.27
		architects_palette: Architect's Palette Fabric 1.6
		architectury: Architectury 3.8.51
		artifacts: Artifacts 6.0.0+fabric
		artifality: Artifality 0.5.5
		attributefix: AttributeFix 13.0.5
		authme: Auth Me 2.2.0
		autoconfig1u: Auto Config v1 Updated 3.2.2
		balm-fabric: Balm 2.4.3+0
		bclib: BCLib 1.3.5
		beaconoverhaul: Beacon Overhaul 1.5.0+1.18
		bedspreads: Bedspreads 1.5.0-1.18
		betterazalea: Better Azalea 1.0.1-SNAPSHOT
		betterdungeons: YUNG's Better Dungeons 1.18-1.0
		betterend: Better End 1.0.3
		betterf3: BetterF3 1.2.2
		betterfpsdist: Better FPS distance Mod 1.18-1.7
		bettermounthud: Better Mount HUD 1.1.4
		betterpingdisplay: Better Ping Display 1.1.1
		betterstrongholds: YUNG's Better Strongholds 1.18.1-1.0.1
		bhmenu: BHMenu-Fabric 1.17.1-1.18.2-1.3
		blockus: Blockus 2.3.11+1.18.1
		blossom: Blossom 1.18.1-1.0.3
		blue_endless_jankson: jankson 1.2.1
		bookshelf: Bookshelf 12.0.23
		borderlessmining: Borderless Mining 1.1.1+1.18
		caffeineconfig: CaffeineConfig 1.0.0
		capes: Capes 1.2.2+1.18
		capybara: Capybara 1.0.4
		cardinal-components-base: Cardinal Components API (base) 4.1.4
		cardinal-components-block: Cardinal Components API (blocks) 4.0.1
		cardinal-components-entity: Cardinal Components API (entities) 4.1.4
		cardinal-components-item: Cardinal Components API (items) 4.0.1
		carrier: Carrier 1.9.1
		cavetweaks: Cave Tweaks 1.0
		cem: Custom Entity Models 0.7.1
		chalk: Chalk 1.2.2
		chat_heads: Chat Heads 0.6.0
		cherishedworlds: Cherished Worlds 2.0.1-1.18
		chiselsandbits: Chisels & Bits 1.2.82
		chunky: Chunky 1.2.164
		citresewn: CIT Resewn 1.0.1+1.18.2
		citresewn-defaults: CIT Resewn: Defaults 1.0.1+1.18.2
		cleancut: CleanCut 1.18-4.0-fabric
		cleardespawn: Clear Despawn 1.1.7
		clickadv: Clickable Advancements Mod 2.5
		cloth-api: Cloth API 3.1.61
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-client-events-v0: Cloth Client Events v0 3.1.61
		cloth-common-events-v1: Cloth Common Events v1 3.1.61
		cloth-config: Cloth Config v6 6.2.57
		cloth-datagen-api-v1: Cloth Datagen v1 3.1.61
		cloth-scissors-api-v1: Cloth Scissors API v1 3.1.61
		cloth-utils-v1: Cloth Utils v1 3.1.61
		coat: Coat 1.0.0-beta.17+mc1.18-pre1
		collective-fabric: Collective (Fabric) 4.9
		colormatic: Colormatic 3.1.0+mc.1.18.1
		com_electronwill_night-config_core: core 3.6.5
		com_electronwill_night-config_toml: toml 3.6.5
		com_eliotlash_mclib_mclib: mclib 18
		com_eliotlash_molang_molang: molang 18
		com_github_llamalad7_mixinextras: mixinextras 0.0.3
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		comforts: Comforts 1.0.3-1.18.1
		companion: Companion 1.2.1
		completeconfig: CompleteConfig 1.4.0
		connectiblechains: Connectible Chains 2.1.0+1.18.1
		continuity: Continuity 1.1.0+1.18
		controlling: Controlling For Fabric 9.0+15
		couplings: Couplings 1.7.1+1.18
		craftingtweaks: Crafting Tweaks 13.0.0
		crawl: Crawl 0.10.2
		creeperoverhaul: Creeper Overhaul 0.3.0
		crowdin-translate: CrowdinTranslate 1.4+1.18
		cullleaves: Cull Leaves 2.3.2
		customstars: Custom Stars 0.7+1.18
		dcch: DCCH 1.0
		decorative_blocks: Decorative Blocks 2.0.4
		despawningeggshatch-fabric: Despawning Eggs Hatch (Fabric) 2.3
		detailab: Detail Armor Bar 2.6.1+1.18-fabric
		dev_isxander_settxi: settxi 2.1.0
		disable_custom_worlds_advice: Disable Custom Worlds Advice 1.4
		dragonloot: DragonLoot 1.0.10
		dual_riders: DualRiders 1.0.5
		dusk: Dusk Mod 1.18.2-1.9
		dyed: Dyed 1.0.2
		dynamicfps: Dynamic FPS 2.1.0
		eatinganimationid: Eating Animation 1.6
		ecologics: Ecologics 1.3.0
		enchantedtooltips: Enchanted ToolTips 1.3.5-1.18
		enhancedblockentities: Enhanced Block Entities 0.5+1.18
		entity_texture_features: Entity Texture Features 2.6.1
		entityculling: EntityCulling-Fabric 1.5.1
		equipmentcompare: Equipment Compare 1.2.12
		expandability: ExpandAbility 5.0.0
		fabric: Fabric API 0.46.6+1.18
		fabric-api-base: Fabric API Base 0.4.2+d7c144a865
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.3+d7c144a865
		fabric-biome-api-v1: Fabric Biome API (v1) 6.0.2+d7c144a865
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.10+3ac43d9565
		fabric-command-api-v1: Fabric Command API (v1) 1.1.7+d7c144a865
		fabric-commands-v0: Fabric Commands (v0) 0.2.6+b4f4f6cd65
		fabric-containers-v0: Fabric Containers (v0) 0.1.19+d7c144a865
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.9+d7c144a865
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.9+3ac43d9565
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.10+a1d9bbf565
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.6+d7c144a865
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.17+d7c144a865
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.9+d7c144a865
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.11+d7c144a865
		fabric-item-api-v1: Fabric Item API (v1) 1.3.1+691a79b565
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.7+3ac43d9565
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.9+d7c144a865
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.7+b4f4f6cd65
		fabric-language-kotlin: Fabric Language Kotlin 1.7.4+kotlin.1.6.21
		fabric-language-scala: Fabric Language Scala 1.1.0+scala.2.13.6
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.13+713c266865
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.9+d7c144a865
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.7+d7c144a865
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.12+b4f4f6cd65
		fabric-models-v0: Fabric Models (v0) 0.3.4+d7c144a865
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.19+d7c144a865
		fabric-networking-v0: Fabric Networking (v0) 0.3.6+b4f4f6cd65
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.5+737332ce65
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.13+d7c144a865
		fabric-particles-v1: Fabric Particles (v1) 0.2.10+526dc1ac65
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.2+ad01bfbd65
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.11+b0b66fc365
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.15+6825030165
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.10+b4f4f6cd65
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.5+d7c144a865
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.19+3ac43d9565
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.12+b4f4f6cd65
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.6+713c266865
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 1.0.2+d7c144a865
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.17+801ec85b60
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.8+d7c144a865
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.12+d7c144a865
		fabric-structure-api-v1: Fabric Structure API (v1) 2.1.3+d7c144a865
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.9+d7c144a865
		fabric-textures-v0: Fabric Textures (v0) 1.0.10+3ac43d9565
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.9+fb3b57b465
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.10+c329913d65
		fabricloader: Fabric Loader 0.13.3
		fabrishot: Fabrishot 1.6.2
		fallingleaves: Falling Leaves 1.9.0+1.18.1
		fallingtree: FallingTree 3.2.1
		fancymenu: FancyMenu 2.6.6
		farmersdelight: Farmer's Delight 1.18.1-0.2.0
		farsight: Farsight Mod 1.18-1.7
		fastbench: FastBench 1.18.1-3
		fastopenlinksandfolders: FastOpenResourcePacks 1.1.0
		ferritecore: FerriteCore 4.1.2
		fiber: fiber 0.23.0-2
		flytre_lib: FlytreLib 1.7.1
		forgeconfigapiport: Forge Config API Port 3.1.1
		geckolib3: Geckolib 3.0.33
		glassential: Glassential 1.3.0
		goblintraders: Goblin Traders 1.5
		goosik-config: goosik-config 0.2.0
		guardvillagers: Guard Villagers Fabric 1.18.1-1.0.11
		harvest_scythes: Harvest Scythes 2.4.1
		iceberg: Iceberg 1.0.38
		illuminations: Illuminations 1.10.2
		imm_ptl_core: Immersive Portals Core 1.2.5
		immersive_portals: Immersive Portals 1.2.5
		incantationem: Incantationem 1.1.3+1.18.1
		indium: Indium 1.0.2-alpha3+mc1.18.1
		infusion_table: Infusion Table 1.0.5
		inventoryhud: Inventory HUD + 3.4.2
		iris: Iris 1.2.0-pre
		ironchests: Iron Chests for Fabric 1.5.4
		itemmodelfix: Item Model Fix 1.0.3+1.18
		jankson: Jankson 4.0.0+j1.2.0
		java: OpenJDK 64-Bit Server VM 17
		kirin: Kirin UI 1.10.0-beta.2
		kleeslabs: KleeSlabs 11.0.0
		konkrete: Konkrete 1.3.3
		kubejs: KubeJS 1801.4.3-build.310
		kyrptconfig: Kyrpt Config 1.2.6-1.18
		lambdabettergrass: LambdaBetterGrass 1.2.2+1.17
		lambdynlights: LambDynamicLights 2.1.0+1.17
		languagereload: Language Reload 1.2.1
		lapisreserve: Lapis Reserve 1.0.8
		lazydfu: LazyDFU 0.1.2
		legendarytooltips: Legendary Tooltips 1.2.4
		levelz: LevelZ 1.2.0
		libgui: LibGui 5.3.0+1.18
		libninepatch: LibNinePatch 1.1.0
		lithium: Lithium 0.7.8
		locksmith: Locksmith 1.0.1
		logprot: Logprot Mod 1.18-1.5
		lovely_snails: Lovely Snails 1.0.3+1.18
		lumiwool: Luminous Wool 1.2.2
		mannequins: Mannequins 2.1.0
		maybe-data: Maybe data 1.2.1-1.18.2
		me_hypherionmc_simple-rpc-common: simple-rpc-common 1.0.20
		megane: megane 7.1.3
		megane-api: megane-api 7.0.0
		megane-applied-energistics-2: megane-applied-energistics-2 7.0.1
		megane-fabric-transfer: megane-fabric-transfer 7.0.0
		megane-reborn-core: megane-reborn-core 7.0.0
		megane-reborn-energy: megane-reborn-energy 7.0.0
		megane-runtime: megane-runtime 7.1.3
		megane-tech-reborn: megane-tech-reborn 7.0.0
		megane-vanilla: megane-vanilla 7.0.0
		midnightlib: MidnightLib 0.4.0
		minecraft: Minecraft 1.18.1
		mm: Manningham Mills 2.3
		mo_glass: Mo Glass 1.6.1-MC1.18.1
		mobscarecrow: Mob Scarecrow 1.2.0
		modmenu: Mod Menu 3.0.1
		morechathistory: MoreChatHistory 1.1.0
		mousetweaks: Mouse Tweaks 2.22
		mousewheelie: Mouse Wheelie 1.8.8+mc1.18-pre5
		nears: Nears 1.1.6
		nofade: No Fade 1.18-2.0.1
		notenoughanimations: NotEnoughAnimations 1.6.0
		notenoughcrashes: Not Enough Crashes 4.1.4+1.18.1
		notes: Notes 1.0.10
		org_anarres_jcpp: jcpp 1.4.14
		org_codehaus_groovy_groovy: groovy 3.0.8
		org_codehaus_groovy_groovy-jsr223: groovy-jsr223 3.0.8
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.6.21
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.6.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.6.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.6.21
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.1
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.1
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.2
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.2
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.2
		org_joml_joml: joml 1.10.2
		org_slf4j_slf4j-api: slf4j-api 1.7.12
		oro_config: OroArmor Config 2.1.0
		owo: oωo 0.5.2+1.18
		oxidized: Oxidized 1.6.1
		paintings: Paintings++ 9.1.0.0
		patchouli: Patchouli 1.18.1-65-FABRIC
		pipe: Pipe 1.6.2
		pistorder: Pistorder 1.5.0
		pollen: Pollen 1.3.1
		polymorph: Polymorph 0.0.20-1.18.2
		presencefootsteps: Presence Footsteps 1.4.0
		pride: Pride Lib 1.1.0+1.17
		publicguiannouncement: Public Gui Announcement 3.2.0.0
		puzzle: Puzzle 1.2.1
		puzzle-base: Puzzle Base 1.2.1
		puzzle-gui: Puzzle GUI 1.2.1
		puzzle-models: Puzzle Models 1.2.1
		puzzle-splashscreen: Puzzle Splash Screen 1.2.1
		q_misc_util: QMiscUtil 1.2.5
		quarryplus: QuarryPlus 18.2.0
		quartzelv: Quartz Elevator 2.1.1+1.18
		raised: Raised 1.0.7
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		reborncore: Reborn Core 5.1.0
		reeses-sodium-options: Reese's Sodium Options 1.4.0
		replanter: Replanter 1.3
		rhino: Rhino 1801.1.9-build.135
		roughlyenoughitems: Roughly Enough Items 7.4.456
		rpgdifficulty: Rpg Difficulty 1.0.11
		saplanting: Saplanting 1.0
		seedfix: Seed Fix 1.0.0
		simple-rpc: Simple Rpc 2.7.2
		slight-gui-modifications: 'Slight' GUI Modifications 2.0.3
		slimyfloor: Slimy Floor 1.18-1.2.2
		smoothboot: Smooth Boot 1.18-1.7.0
		sodium: Sodium 0.4.0-alpha6+build.14
		sodium-extra: Sodium Extra 0.4.0
		someforgepatchesported: Some Forge Patches Ported 1.0.2
		spark: spark 1.9.1
		spruceui: SpruceUI 3.3.2+1.17
		spyglass-improvements: Spyglass Improvements 1.1+mc1.18.1+fabric
		starlight: Starlight 1.0.0+fabric.d0a3220
		static-content: Static Content 1.0.1-1.16.2
		staticdata: Static Data 1.1.2
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		team_reborn_energy: Energy 2.2.0
		techreborn: Tech Reborn 5.1.0
		terraform-wood-api-v1: Terraform Wood API (v1) 2.0.2
		terralith: Terralith for Fabric 2.0.12
		thonkutil-base: ThonkUtil Base 1.5.1+31ad4eb1c8
		thonkutil-capes-v1: ThonkUtil Capes (v1) 1.2.2+befce073c8
		thonkutil-potions-v0: ThonkUtil Potions (v0) 1.3.1+befce073c8
		thonkutil-trades-v1: ThonkUtil Trades (v1) 1.1.8+d77526a2c8
		tiefix: TieFix 1.9.0
		timeoutout: TimeOut Out 1.0.0+1.18
		toolstats: ToolStats 8.0.6
		tooltipfix: ToolTip Fix 1.0.4-1.18
		trinketofundying: Trinket of Undying 2.0.1-1.18
		trinkets: Trinkets 3.2.0
		tweed4_annotated: tweed4_annotated 1.3.0+mc1.18-pre2
		tweed4_base: tweed4_base 1.5.0+mc1.18-pre2
		tweed4_data: tweed4_data 1.2.1+mc1.18-pre2
		tweed4_data_hjson: tweed4_data_hjson 1.1.0+mc1.18-pre2
		tweed4_tailor_coat: tweed4_tailor_coat 1.1.2+mc1.18-pre2
		tweed4_tailor_screen: tweed4_tailor_screen 1.1.1+mc1.18-pre2
		twigs: Twigs 1.1.2
		visuality: Visuality 0.4.1
		waystones: Waystones 9.0.4
		wolveswitharmor: Wolves With Armor 1.7.1-1.18.2
		wthit: wthit 4.5.5
		xaerominimap: Xaero's Minimap 22.3.0
		xaeroworldmap: Xaero's World Map 1.20.3.1
		yigd: You're in Grave Danger 1.2.22
		yosbr: YOSBR 0.1.1
		yungsapi: YUNG's API 1.18-Fabric-36
		zoomify: Zoomify 1.1.0
	Launched Version: fabric-loader-0.13.3-1.18.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce GTX 1650 Ti/PCIe/SSE2 GL version 3.2.0 NVIDIA 496.49, NVIDIA Corporation
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: 12x Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
	Suspected Mods: Minecraft (minecraft), Fabric Loader (fabricloader), 'Slight' GUI Modifications (slight-gui-modifications), Cloth Config v6 (cloth-config)

**Comment by SansSkele76** [comment]
If I was supposed to leave this issue elsewhere, please let me know
